### ISSUE TITLE
How to integerate this module 

### ISSUE THREAD

**Issue by babitakapoor112** [lizhming/ScreenCaptureSecure#2]
How to call this module. Is there any kind of function we need to use or we just need to use 
import ScreenCaptureSecure from 'react-native-screen-capture-secure';
 
// TODO: What to do with the module?
ScreenCaptureSecure;

I have used the above code but nothing happens.
Please suggest the appropriate example to use this library.

**Comment by lizhming** [comment]
I just updated the Readme.
You can use enableSecure and disableSecure function.
```
ScreenCaptureSecure.enableSecure();
ScreenCaptureSecure.disableSecure();
```
